### ISSUE TITLE
🐛 Bug: Incorrect decrypted file name for duplicated files when in the same location.

### ISSUE THREAD

**Issue by sh-dv** [samuel-lucas6/Kryptor#28]
### Description

Situation : I have a file called `Document.txt`, i encrypt this file and have the new file named `Document.txt.kryptor`, then I encrypt the same `Document.txt` file and get another encrypted file called `Document.txt (2).kryptor`. When trying to decrypt the second file `Document.txt (2).kryptor` everything works except the new decrypted file is called `Document.txt (2)`. this file won't open unless you rename it (remove brackets) to `Document.txt`.

This situation only happens when there is already another file having the same name.

### Platform Info
 - OS: Windows
 - Version: 3.0.3

**Comment by samuel-lucas6** [comment]
Hi @sh-dv,

Thanks for the great find! This unique rename implementation has been a bit of a hassle. I'll take a look at your pull request.
