### ISSUE TITLE
✨ Feedback: There looks to be a false positive reported by VirusTotal

### ISSUE THREAD

**Issue by brian6932** [samuel-lucas6/Kryptor#5]
https://www.virustotal.com/gui/file/60cd1b4cbd3890c332415fb32535f782ac11b4af55a8eb715dc9ce9e7fee3e71/detection

**Comment by samuel-lucas6** [comment]
Hi brian,

Thanks for bringing this to my attention. I have reported the false positive to SecureAPlus. It looks like all of the Kryptor files get one false positive detection (usually from McAfee), so I'll try to report those as false positives too. Unfortunately, they might get detected again when I release a new version.
